name: Download and Upload Jav Videos

on:
  schedule:
    - cron: '0 */24 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  process_videos:
    runs-on: ubuntu-latest
    env:
      PIXELDRAIN_API_KEY: ${{ secrets.PIXELDRAIN_API_KEY }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y aria2
          pip install yt-dlp requests

      - name: Download Videos with yt-dlp + aria2c
        run: |
          mkdir -p downloads
          while IFS= read -r url; do
            yt-dlp \
              --external-downloader aria2c \
              --external-downloader-args "-x 20 -j 20 -s 20 -k 100M" \
              -o "downloads/%(title)s.%(ext)s" "$url"
          done < links.txt

      - name: Upload to PixelDrain
        run: |
          for file in downloads/*; do
            curl -X POST -F "file=@$file" \
              -H "Authorization: Bearer $PIXELDRAIN_API_KEY" \
              https://pixeldrain.com/api/file
          done
