name: Run Shell Scripts and Save Artifacts

on:
 workflow_dispatch:

jobs:
  run-shell-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: |
          chmod +x start.sh
          chmod +x main.sh

      - name: Run start.sh
        run: ./start.sh

      - name: Run main.sh
        run: ./main.sh

      - name: Upload sources.txt
        uses: actions/upload-artifact@v4
        with:
          name: sources
          path: sources.txt

      - name: Upload links.txt
        uses: actions/upload-artifact@v4
        with:
          name: links
          path: links.txt
