name: Run Shell Scripts and Save Artifacts

on:
  schedule:
    - cron: '0 */24 * * *'  # Run every 6 hours
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  run-shell-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: |
          chmod +x start.sh
          chmod +x main.sh

      - name: Run start.sh
        run: ./start.sh

      - name: Run main.sh
        run: ./main.sh

      - name: Move sources.txt and links.txt to docs folder
        run: |
          mkdir -p docs
          mv failed.txt docs/failed.txt
          mv final_links.csv docs/links.csv
          mv sources.txt docs/sources.txt
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add docs/sources.txt docs/failed.txt docs/links.csv
          git commit -m "Add sources.txt and links.txt to docs folder"
          git push
